### ISSUE TITLE
flake8 on `*.pyi` still reports missing docstrings?

### ISSUE THREAD

**Issue by jenstroeger** [PyCQA/flake8-pyi#48]
Thank you for this plugin, it looks useful! However, I have two questions regarding its use.

1. After adding it to the pre-commit configuration
    ```
      - repo: https://github.com/pycqa/flake8
        rev: 4.0.1
        hooks:
        - id: flake8
          files: ^package/|^tests/|setup.py
          additional_dependencies: [flake8-builtins==1.5.3,flake8-docstrings==1.6.0,flake8-pyi==20.10.0,flake8-rst-docstrings==0.2.3,pep8-naming==0.12.1]
    ```
    nothing is reported, but then…
2. Running `flake8` from the terminal directly I get a bunch of D100, D101, D102 that the docstrings are missing in all `*.pyi` files.

Not quite sure yet what’s going on here, but if you can shed some light on this that’d be great!
